// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HoverContainer: typeof import('./src/components/HoverContainer.vue')['default']
    IconMdiAccountSupervisorCircle: typeof import('~icons/mdi/account-supervisor-circle')['default']
    IconMdiMessageAlert: typeof import('~icons/mdi/message-alert')['default']
    NaiveProvider: typeof import('./src/components/NaiveProvider.vue')['default']
  }
}

export { }
