// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    GlobalHeader: typeof import('./src/components/GlobalHeader/GlobalHeader.vue')['default']
    HoverContainer: typeof import('./src/components/common/HoverContainer.vue')['default']
    IconMdiBell: typeof import('~icons/mdi/bell')['default']
    IconMdiChat: typeof import('~icons/mdi/chat')['default']
    IconMdiTextSearch: typeof import('~icons/mdi/text-search')['default']
    NaiveProvider: typeof import('./src/components/common/NaiveProvider.vue')['default']
  }
}

export { }
