// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArticlesList: typeof import('./src/components/article/ArticlesList.vue')['default']
    ArticlesListItem: typeof import('./src/components/article/ArticlesListItem.vue')['default']
    AvatarDropdown: typeof import('./src/components/common/globalheader/AvatarDropdown.vue')['default']
    GlobalContent: typeof import('./src/components/common/globalcontent/GlobalContent.vue')['default']
    GlobalHeader: typeof import('./src/components/common/globalheader/GlobalHeader.vue')['default']
    HoverContainer: typeof import('./src/components/common/HoverContainer.vue')['default']
    MessageDropdown: typeof import('./src/components/common/globalheader/MessageDropdown.vue')['default']
    NaiveProvider: typeof import('./src/components/common/NaiveProvider.vue')['default']
    SignInForm: typeof import('./src/components/login/SignInForm.vue')['default']
    SignUpForm: typeof import('./src/components/login/SignUpForm.vue')['default']
  }
}

export { }
